# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71461f5783365e6fbba60d8a19f62af2c9de24b23bc5c88244e7920606502bb9ff97390b50ab078ab98978595c0ff4cbd9bdf29c24f2818f21c432380f8180b2

test:
  secret_key_base: 5caaa6285f4c79bbc8a2a35774d86b5ca60e738a053615e8b44907938d59b63c69989a5b473512fbe4159afba1e1586addc57c5d0875b2b79fa087f039ddbe5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
